CREATE TABLE ENERGY_DATA (
    record_id        NUMBER PRIMARY KEY,
    record_date      DATE,
    energy_source    VARCHAR2(20),
    generated_energy NUMBER(8,2),   -- MWh
    consumed_energy  NUMBER(8,2),   -- MWh
    location         VARCHAR2(30)
);

INSERT INTO ENERGY_DATA VALUES (1,  DATE '2026-10-01', 'Solar', 520, 480, 'Chennai');
INSERT INTO ENERGY_DATA VALUES (2,  DATE '2026-10-01', 'Wind',  430, 450, 'Coimbatore');
INSERT INTO ENERGY_DATA VALUES (3,  DATE '2026-10-01', 'Hydro', 610, 540, 'Madurai');
INSERT INTO ENERGY_DATA VALUES (4,  DATE '2026-10-01', 'Solar', 390, 410, 'Trichy');
INSERT INTO ENERGY_DATA VALUES (5,  DATE '2026-10-01', 'Wind',  350, 330, 'Salem');

INSERT INTO ENERGY_DATA VALUES (6,  DATE '2026-10-02', 'Solar', 540, 495, 'Chennai');
INSERT INTO ENERGY_DATA VALUES (7,  DATE '2026-10-02', 'Wind',  470, 440, 'Coimbatore');
INSERT INTO ENERGY_DATA VALUES (8,  DATE '2026-10-02', 'Hydro', 590, 560, 'Madurai');
INSERT INTO ENERGY_DATA VALUES (9,  DATE '2026-10-02', 'Solar', 405, 400, 'Trichy');
INSERT INTO ENERGY_DATA VALUES (10, DATE '2026-10-02', 'Wind',  320, 345, 'Salem');

INSERT INTO ENERGY_DATA VALUES (11, DATE '2026-10-03', 'Solar', 505, 510, 'Chennai');
INSERT INTO ENERGY_DATA VALUES (12, DATE '2026-10-03', 'Wind',  495, 460, 'Coimbatore');
INSERT INTO ENERGY_DATA VALUES (13, DATE '2026-10-03', 'Hydro', 625, 570, 'Madurai');
INSERT INTO ENERGY_DATA VALUES (14, DATE '2026-10-03', 'Solar', 415, 395, 'Trichy');
INSERT INTO ENERGY_DATA VALUES (15, DATE '2026-10-03', 'Wind',  360, 350, 'Salem');

INSERT INTO ENERGY_DATA VALUES (16, DATE '2026-10-04', 'Solar', 560, 520, 'Chennai');
INSERT INTO ENERGY_DATA VALUES (17, DATE '2026-10-04', 'Wind',  440, 455, 'Coimbatore');
INSERT INTO ENERGY_DATA VALUES (18, DATE '2026-10-04', 'Hydro', 600, 585, 'Madurai');
INSERT INTO ENERGY_DATA VALUES (19, DATE '2026-10-04', 'Solar', 380, 420, 'Trichy');
INSERT INTO ENERGY_DATA VALUES (20, DATE '2026-10-04', 'Wind',  375, 340, 'Salem');

INSERT INTO ENERGY_DATA VALUES (21, DATE '2026-10-05', 'Solar', 575, 530, 'Chennai');
INSERT INTO ENERGY_DATA VALUES (22, DATE '2026-10-05', 'Wind',  480, 470, 'Coimbatore');
INSERT INTO ENERGY_DATA VALUES (23, DATE '2026-10-05', 'Hydro', 640, 590, 'Madurai');
INSERT INTO ENERGY_DATA VALUES (24, DATE '2026-10-05', 'Solar', 425, 405, 'Trichy');
INSERT INTO ENERGY_DATA VALUES (25, DATE '2026-10-05', 'Wind',  340, 360, 'Salem');

COMMIT;

-- 1. Display energy records with date, source, generated, consumed, location
SELECT record_date, energy_source, generated_energy, consumed_energy, location
FROM ENERGY_DATA
ORDER BY record_date, location;

-- 2. Total energy generated by each energy source
SELECT energy_source, SUM(generated_energy) AS total_generated
FROM ENERGY_DATA
GROUP BY energy_source;

-- 3. Daily energy consumption
SELECT record_date, SUM(consumed_energy) AS daily_consumption
FROM ENERGY_DATA
GROUP BY record_date
ORDER BY record_date;

-- 4. Energy surplus or deficit for each record
SELECT record_id, location, generated_energy, consumed_energy,
       (generated_energy - consumed_energy) AS balance,
       CASE
           WHEN generated_energy > consumed_energy THEN 'Surplus'
           WHEN generated_energy < consumed_energy THEN 'Deficit'
           ELSE 'Balanced'
       END AS status
FROM ENERGY_DATA;

-- 5. Total energy generation for each location
SELECT location, SUM(generated_energy) AS total_generation
FROM ENERGY_DATA
GROUP BY location
ORDER BY total_generation DESC;

-- 1. Function: surplus or deficit for a given record
CREATE OR REPLACE FUNCTION fn_energy_balance (p_record_id IN NUMBER)
RETURN NUMBER
IS
    v_balance NUMBER;
BEGIN
    SELECT generated_energy - consumed_energy
    INTO v_balance
    FROM ENERGY_DATA
    WHERE record_id = p_record_id;

    RETURN v_balance;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN NULL;
END;
/

-- Test
SET SERVEROUTPUT ON;
BEGIN
    DBMS_OUTPUT.PUT_LINE('Balance for record 2: ' || fn_energy_balance(2));
END;
/

-- 2. Procedure: insert daily energy generation and consumption
CREATE OR REPLACE PROCEDURE sp_insert_energy (
    p_record_id IN NUMBER,
    p_date      IN DATE,
    p_source    IN VARCHAR2,
    p_generated IN NUMBER,
    p_consumed  IN NUMBER,
    p_location  IN VARCHAR2
)
IS
BEGIN
    INSERT INTO ENERGY_DATA
    VALUES (p_record_id, p_date, p_source, p_generated, p_consumed, p_location);

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Record inserted successfully.');
EXCEPTION
    WHEN DUP_VAL_ON_INDEX THEN
        DBMS_OUTPUT.PUT_LINE('Error: record_id already exists.');
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error: ' || SQLERRM);
END;
/

-- Test
BEGIN
    sp_insert_energy(26, DATE '2026-10-06', 'Solar', 550, 500, 'Chennai');
END;
/

-- 3. Procedure: source-wise and location-wise energy report
CREATE OR REPLACE PROCEDURE sp_energy_report
IS
    CURSOR c_report IS
        SELECT energy_source, location,
               SUM(generated_energy) AS total_gen,
               SUM(consumed_energy)  AS total_con,
               SUM(generated_energy) - SUM(consumed_energy) AS net_balance
        FROM ENERGY_DATA
        GROUP BY energy_source, location
        ORDER BY energy_source, location;
BEGIN
    DBMS_OUTPUT.PUT_LINE(RPAD('Source', 10) || RPAD('Location', 15) ||
                         RPAD('Generated', 12) || RPAD('Consumed', 12) || 'Net');
    DBMS_OUTPUT.PUT_LINE(RPAD('-', 55, '-'));

    FOR r IN c_report LOOP
        DBMS_OUTPUT.PUT_LINE(RPAD(r.energy_source, 10) || RPAD(r.location, 15) ||
                             RPAD(r.total_gen, 12) || RPAD(r.total_con, 12) ||
                             r.net_balance);
    END LOOP;
END;
/

-- Run
SET SERVEROUTPUT ON;
EXEC sp_energy_report;

